apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightreservation
  labels:
    app: flightreservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightreservation
  template:
    metadata:
      labels:
        app: flightreservation
    spec:
      containers:
        - name: flightreservation
          image: username/flightreservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
